---
- name: base
  title: Wazuh Base Engine Settings
  description: >
    Fields for Wazuh Base Engine Settings.
  type: group
  group: 2
  fields:
    - name: engine.index_raw_events
      type: boolean
      level: custom
      description: >
        When set to `true`, the engine will index raw events.
