version: 2
updates:
  - directories:
      - "/plugins/*"
    open-pull-requests-limit: 1
    package-ecosystem: gradle
    schedule:
      interval: weekly
      day: "friday"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    commit-message:
      prefix: "dependabot:"
