updates:
  - directories:
      - "/plugins/setup"
      - "/plugins/command-manager"
    open-pull-requests-limit: 1
    package-ecosystem: gradle
    schedule:
      interval: weekly
      day: "friday"
version: 2