---
- name: host
  reusable:
    top_level: true
    expected:
      - { at: agent, as: host }
  fields:
    - name: memory.total
      description: >
        Total memory, in Bytes.
      type: long
      level: custom
      example: 52584
    - name: memory.free
      description: >
        Free memory, in Bytes.
      type: long
      level: custom
      example: 87191
    - name: memory.used
      description: >
        Used memory, in Bytes.
      type: long
      level: custom
      example: 123456
    - name: memory.usage
      type: scaled_float
      scaling_factor: 100
      level: custom
      description: >
        Percent memory used, between 0 and 1.
      example: 0.75
    - name: cpu.name
      description: >
        Name/model of the CPU.
      type: keyword
      level: custom
      example: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    - name: cpu.cores
      description: >
        Number of CPU cores.
      type: short
      level: custom
      example: 8
    - name: cpu.speed
      description: >
        CPU clock speed in MHz.
      type: long
      level: custom
      example: 3600
    - name: serial_number
      level: custom
      type: keyword
      description: >
        Serial Number of the device.
      example: DJGAQS4CW5
