system("
    if [ #{ARGV[0]} = 'up' ]; then
        echo 'Executing pre-start script.'
        bash ./pre-start.sh
    fi
")

Vagrant.configure("2") do |config|
    config.vm.define "indexer_1" do |indexer_1|
        indexer_1.vm.box = "generic/alma9"
        indexer_1.vm.synced_folder ".", "/vagrant"
        indexer_1.vm.network "private_network", ip: "192.168.56.10"
        indexer_1.vm.hostname = "indexer-1"
        indexer_1.vm.provider "libvirt" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end
        indexer_1.vm.provision "shell", inline: <<-SHELL
            systemctl stop firewalld
            systemctl disable firewalld
            yum clean all
            yum install jq unzip tar -y
            # Add indexer-2 to /etc/hosts
            echo "192.168.56.11 indexer-2" >> /etc/hosts
            # Copy generated certificates
            cp /vagrant/wazuh-certificates.tar /home/vagrant/wazuh-certificates.tar
            # Copy test scripts
            cp -r /vagrant/scripts /home/vagrant/scripts
            chown -R vagrant:vagrant /home/vagrant/scripts
        SHELL
    end
    config.vm.define "indexer_2" do |indexer_2|
        indexer_2.vm.box = "generic/ubuntu2204"
        indexer_2.vm.synced_folder ".", "/vagrant"
        indexer_2.vm.network "private_network", ip: "192.168.56.11"
        indexer_2.vm.hostname = "indexer-2"
        indexer_2.vm.provider "libvirt" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end
        indexer_2.vm.provision "shell", inline: <<-SHELL
            systemctl stop ufw
            systemctl disable ufw
            apt-get install curl jq unzip tar -y
            # Add indexer-1 to /etc/hosts
            echo "192.168.56.10 indexer-1" >> /etc/hosts
            # Copy generated certificates
            cp /vagrant/wazuh-certificates.tar /home/vagrant/wazuh-certificates.tar
            # Copy test scripts
            cp -r /vagrant/scripts /home/vagrant/scripts
            chown -R vagrant:vagrant /home/vagrant/scripts
        SHELL
    end
end