name: "Branch Resolver"
description: "Select the appropriate branch for dependent repositories based on the current branch"
inputs:
  branch:
    description: "Branch to check"
    required: true
outputs:
  wazuh_indexer_security_analytics_branch:
    description: "Branch to use in wazuh-indexer-security-analytics repository."
    value: ${{ steps.resolve.outputs.wazuh_indexer_security_analytics_branch }}
runs:
  using: "composite"
  steps:
    - id: resolve
      run: |
        eval $(${{ github.action_path }}/resolve_branches.sh "${{ inputs.branch }}" | awk -F= '{gsub("-", "_", $1); print toupper($1)"_BRANCH="$2}')
        echo "wazuh_indexer_security_analytics_branch=$WAZUH_INDEXER_SECURITY_ANALYTICS_BRANCH" >> $GITHUB_OUTPUT
      shell: bash
