---
- name: password
  title: Password
  type: group
  group: 2
  reusable:
    top_level: false
    expected:
      - { at: user, as: password }
  description: >
    Custom password information for users, relevant to inventory data.
  fields:
    - name: status
      type: keyword
      level: custom
      description: >
        Password status (e.g., active).
    - name: hash_algorithm
      type: keyword
      level: custom
      description: >
        Algorithm used to hash the password.
    - name: last_change
      type: integer
      level: custom
      description: >
        Days since epoch when password was last changed.
    - name: min_days_between_changes
      type: integer
      level: custom
      description: >
        Minimum days between password changes.
    - name: max_days_between_changes
      type: integer
      level: custom
      description: >
        Maximum days between password changes.
    - name: warning_days_before_expiration
      type: integer
      level: custom
      description: >
        Days before expiration to warn user.
    - name: inactive_days
      type: integer
      level: custom
      description: >
        Number of days of inactivity before disabling the password.
    - name: expiration_date
      type: date
      level: custom
      description: >
        Password expiration date (epoch).
    - name: last_set_time
      type: date
      level: custom
      description: >
        Time the password was last set (epoch).
