---
name: wazuh-states-inventory-browser-extensions
fields:
  base:
    fields:
      tags: []
  agent:
    fields:
      groups: []
      id: {}
      name: {}
      version: {}
      host:
        fields:
          architecture: {}
          hostname: {}
          ip: {}
          os:
            fields:
              name: {}
              platform: {}
              type: {}
              version: {}
  checksum:
    fields: "*"
  browser:
    fields: "*"
  package:
    fields:
      name: {}
      id: {}
      version: {}
      description: {}
      vendor: {}
      build_version: {}
      path: {}
      reference: {}
      permissions: {}
      type: {}
      enabled: {}
      autoupdate: {}
      persistent: {}
      from_webstore: {}
      installed: {}
      visible: {}
  file:
    fields:
      hash:
        fields:
          sha256: {}
  user:
    fields:
      id: {}
  state:
    fields: "*"
  wazuh:
    fields: "*"

