- name: package
  title: Package
  group: 2
  short: These fields contain information about an installed software package.
  description: >
    These fields contain information about an installed software package.
    It contains general information about a package, such as name, version or size.
    It also contains installation details, such as time or location.
  type: group
  fields:
    - name: size
      type: unsigned_long
      level: custom
      description: >
        Package size in bytes.
