[book]
title = "Wazuh Indexer technical documentation"
authors = ["Wazuh Indexer Team"]
description = "Technical documentation for the Wazuh Indexer, including development guidance and the reference manual."
language = "en"
src = "."

[build]
build-dir = "book"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/wazuh/wazuh-indexer-plugins"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true

[output.html.playground]
editable = false
copyable = true


