name: CI

# This workflow runs when any of the following occur:
# - On push
on:
    push:
        
jobs:
    call-build-workflow:
        uses: ./.github/workflows/5_builderpackage_plugins.yml
        secrets: inherit