name: (5.x) Build Wazuh Common Schema

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "ecs/**/*.json"
      - "ecs/**/*.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wcs:
    name: Build Wazuh Common Schema
    if: github.repository == 'wazuh/wazuh-indexer-plugins'
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Update module list
        run: bash ecs/generator/update_module_list.sh

      - name: Generate WCS
        env:
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
        run: bash ecs/generator/generate_schema.sh

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.INDEXER_BOT_TOKEN }}
          COMMITER_EMAIL: ${{ secrets.INDEXER_BOT_EMAIL }}
          COMMITTER_USERNAME: "Wazuh Indexer Bot"
          SSH_PRIVATE_KEY: ${{ secrets.INDEXER_BOT_PRIVATE_SSH_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.INDEXER_BOT_PUBLIC_SSH_KEY }}
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
        run: bash ecs/generator/push_schema.sh

      - name: Display pull request link
        if: ${{ success() }}
        run: echo "::notice::Pull request link => $(cat /tmp/pull_request_link.txt)"
     
