run-name: Build ${{ inputs.plugin }} plugin | ${{ inputs.id  }}
name: (5.x) Build packages

permissions:
  contents: read
  packages: read

# This workflow runs when any of the following occur:
# - Run manually
# - Invoked from another workflow
on:
  workflow_dispatch:
    inputs:
      revision:
        description: "Revision"
        type: string
        default: "0"
      plugin:
        description: "Name of the plugin to build"
        type: string
        default: "setup"
      id:
        description: "ID used to identify the workflow uniquely."
        type: string
        required: false
  workflow_call:
    inputs:
      revision:
        description: "Revision"
        type: string
        default: "0"
      plugin:
        description: "Name of the plugin to build"
        type: string
        default: "setup"
      id:
        description: "ID used to identify the workflow uniquely."
        type: string
        required: false

# ==========================
# Bibliography
# ==========================
#
# * Reusable workflows: limitations
#   | https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations
# * Using matrix in reusable workflows:
#   | https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow
# * Reading input from the called workflow
#   | https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
# * Ternary operator
#   | https://docs.github.com/en/actions/learn-github-actions/expressions#example

jobs:
  branches:
    runs-on: ubuntu-24.04
    outputs:
      security_analytics_plugin_ref: ${{ steps.branches.outputs.wazuh_indexer_security_analytics_branch }}
      common_utils_plugin_ref: ${{ steps.branches.outputs.wazuh_indexer_common_utils_branch }}
    steps:
      - uses: actions/checkout@v6
      - name: Resolve branches
        id: branches
        uses: wazuh/wazuh-indexer/.github/actions/5_builderpackage_indexer_branch_resolver@main
        with:
          branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

  get-version:
    runs-on: ubuntu-24.04
    needs: branches
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          sparse-checkout: |
            VERSION.json
      - name: Get version
        id: version
        run: echo "version=$(jq -r .version<VERSION.json)" >> "$GITHUB_OUTPUT"

  publish-common-utils:
    runs-on: ubuntu-24.04
    needs: [branches, get-version]
    steps:
      - name: Restore Maven Local Cache
        id: cache-common-utils
        uses: actions/cache/restore@v5
        with:
          path: ~/.m2/repository
          key: m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.get-version.outputs.version }}-r${{ inputs.revision }}
          restore-keys: |
            m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.get-version.outputs.version }}-
            m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-
      - name: Publish to Maven Local
        if: steps.cache-common-utils.outputs.cache-hit != 'true'
        uses: wazuh/wazuh-indexer-common-utils/.github/actions/5_local_maven_publisher@main
        with:
          version: ${{ needs.get-version.outputs.version }}
          revision: ${{ inputs.revision }}
          reference: ${{ needs.branches.outputs.common_utils_plugin_ref }}
      - name: Cache Maven Local
        if: steps.cache-common-utils.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ~/.m2/repository
          key: m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.get-version.outputs.version }}-r${{ inputs.revision }}

  publish-security-analytics:
    runs-on: ubuntu-24.04
    needs: [branches, get-version, publish-common-utils]
    if: inputs.plugin == 'content-manager'
    steps:
      - name: Restore Maven Local Cache
        id: cache-security-analytics
        uses: actions/cache/restore@v5
        with:
          path: ~/.m2/repository
          key: m2-sap-with-deps-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.branches.outputs.security_analytics_plugin_ref }}-${{ needs.get-version.outputs.version }}-r${{ inputs.revision }}
          restore-keys: |
            m2-sap-with-deps-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.branches.outputs.security_analytics_plugin_ref }}-${{ needs.get-version.outputs.version }}-
            m2-sap-with-deps-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.branches.outputs.security_analytics_plugin_ref }}-
      - name: Restore Maven Local Cache (common-utils)
        if: steps.cache-security-analytics.outputs.cache-hit != 'true'
        uses: actions/cache/restore@v5
        with:
          path: ~/.m2/repository
          key: m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.get-version.outputs.version }}-r${{ inputs.revision }}
          restore-keys: |
            m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.get-version.outputs.version }}-
            m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-
      - name: Publish to Maven Local
        if: steps.cache-security-analytics.outputs.cache-hit != 'true'
        uses: wazuh/wazuh-indexer-security-analytics/.github/actions/5_local_maven_publisher@main
        with:
          version: ${{ needs.get-version.outputs.version }}
          revision: ${{ inputs.revision }}
          reference: ${{ needs.branches.outputs.security_analytics_plugin_ref }}
      - name: Cache Maven Local
        if: steps.cache-security-analytics.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ~/.m2/repository
          key: m2-sap-with-deps-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.branches.outputs.security_analytics_plugin_ref }}-${{ needs.get-version.outputs.version }}-r${{ inputs.revision }}

  build:
    needs: [branches, get-version, publish-common-utils, publish-security-analytics]
    runs-on: ubuntu-24.04
    permissions:
      actions: read
    if: |
      always() &&
      needs.branches.result == 'success' &&
      needs.get-version.result == 'success' &&
      needs.publish-common-utils.result == 'success' &&
      (needs.publish-security-analytics.result == 'success' || needs.publish-security-analytics.result == 'skipped')
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle # Used for caching
        uses: gradle/actions/setup-gradle@v6

      - name: Restore Maven Local Cache (common-utils)
        if: inputs.plugin != 'content-manager'
        uses: actions/cache/restore@v5
        with:
          path: ~/.m2/repository
          key: m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.get-version.outputs.version }}-r${{ inputs.revision }}
          restore-keys: |
            m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.get-version.outputs.version }}-
            m2-common-utils-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-

      - name: Restore Maven Local Cache (security-analytics with deps)
        if: inputs.plugin == 'content-manager'
        uses: actions/cache/restore@v5
        with:
          path: ~/.m2/repository
          key: m2-sap-with-deps-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.branches.outputs.security_analytics_plugin_ref }}-${{ needs.get-version.outputs.version }}-r${{ inputs.revision }}
          restore-keys: |
            m2-sap-with-deps-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.branches.outputs.security_analytics_plugin_ref }}-${{ needs.get-version.outputs.version }}-
            m2-sap-with-deps-${{ github.ref_name }}-${{ needs.branches.outputs.common_utils_plugin_ref }}-${{ needs.branches.outputs.security_analytics_plugin_ref }}-

      - name: Build with Gradle
        working-directory: ./plugins/${{ inputs.plugin }}
        run: ./gradlew build -Dversion=${{ needs.get-version.outputs.version }} -Drevision=${{ inputs.revision }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.plugin }}-${{ needs.get-version.outputs.version }}.${{ inputs.revision }}.zip
          path: plugins/${{ inputs.plugin }}/build/distributions/wazuh-indexer-${{ inputs.plugin }}-${{ needs.get-version.outputs.version }}.${{ inputs.revision }}.zip
          if-no-files-found: error
